name: flutter_timetable_view
description: Timetable Widget Package for for Flutter
version: 0.2.0
homepage: https://github.com/yamarkz

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
